#!bin/bash 

#git add ./README.md
git add ./git_add
git add ./info.txt
git add ./sim/work/run_icarus
git add ./sim/testbenches/example/testbench.v
git add ./rtl_src/sdfm.v
git add ./rtl_src/channel.v
git add ./rtl_src/rcu.v
git add ./rtl_src/regmap.v
git add ./rtl_src/filt.v
